# Generated by Django 5.0.7 on 2024-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("affiliation", models.CharField(max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="authors/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceProceedings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("conference_name", models.CharField(max_length=200)),
                ("conference_location", models.CharField(max_length=200)),
                ("conference_date", models.DateField()),
                ("abstract", models.TextField()),
                (
                    "slides",
                    models.FileField(blank=True, null=True, upload_to="slides/"),
                ),
                ("paper", models.FileField(blank=True, null=True, upload_to="papers/")),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                ("code", models.URLField(blank=True, null=True)),
                ("doi", models.URLField()),
                ("authors", models.ManyToManyField(to="academic.author")),
            ],
        ),
        migrations.CreateModel(
            name="JournalArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("journal_name", models.CharField(max_length=200)),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("issue", models.IntegerField(blank=True, null=True)),
                ("publication_date", models.DateField()),
                ("abstract", models.TextField()),
                (
                    "slides",
                    models.FileField(blank=True, null=True, upload_to="slides/"),
                ),
                ("paper", models.FileField(blank=True, null=True, upload_to="papers/")),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                ("code", models.URLField(blank=True, null=True)),
                ("doi", models.URLField()),
                ("authors", models.ManyToManyField(to="academic.author")),
            ],
        ),
        migrations.CreateModel(
            name="Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("abstract", models.TextField()),
                ("doi", models.URLField()),
                ("authors", models.ManyToManyField(to="academic.author")),
            ],
        ),
    ]
