# Generated by Django 5.0.7 on 2024-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalarticle",
            name="poster",
        ),
        migrations.AddField(
            model_name="thesis",
            name="thesis",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conferenceproceedings",
            name="doi",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conferenceproceedings",
            name="paper",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conferenceproceedings",
            name="poster",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conferenceproceedings",
            name="slides",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="doi",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="paper",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalarticle",
            name="slides",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="doi",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Preprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                ("abstract", models.TextField()),
                ("slides", models.URLField(blank=True, null=True)),
                ("paper", models.URLField(blank=True, null=True)),
                ("code", models.URLField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="academic.author")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("photo", models.URLField()),
                (
                    "conference_papers",
                    models.ManyToManyField(to="academic.conferenceproceedings"),
                ),
                (
                    "journal_papers",
                    models.ManyToManyField(to="academic.journalarticle"),
                ),
            ],
        ),
    ]
