# Generated by Django 5.0.7 on 2024-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_remove_journalarticle_poster_thesis_thesis_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConferenceProceedings",
            new_name="ConferenceProceeding",
        ),
        migrations.AddField(
            model_name="project",
            name="preprints",
            field=models.ManyToManyField(to="academic.preprint"),
        ),
    ]
