# Generated by Django 5.0.7 on 2024-09-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0003_rename_conferenceproceedings_conferenceproceeding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="conference_papers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="journal_papers",
        ),
        migrations.RemoveField(
            model_name="project",
            name="preprints",
        ),
        migrations.AddField(
            model_name="conferenceproceeding",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.project",
            ),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.project",
            ),
        ),
        migrations.AddField(
            model_name="preprint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.project",
            ),
        ),
        migrations.AddField(
            model_name="thesis",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.project",
            ),
        ),
    ]
