# Generated by Django 5.0.7 on 2024-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_remove_project_conference_papers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
