# Generated by Django 5.0.7 on 2024-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0005_author_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="affiliation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
