# Generated by Django 5.0.7 on 2024-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0006_alter_author_affiliation_alter_author_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="photo",
            field=models.CharField(),
        ),
    ]
