# Generated by Django 5.0.7 on 2024-10-02 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0007_alter_project_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalarticle",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="journalarticle",
            name="project",
        ),
        migrations.RemoveField(
            model_name="preprint",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="preprint",
            name="project",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="thesis",
            name="project",
        ),
        migrations.DeleteModel(
            name="ConferenceProceeding",
        ),
        migrations.DeleteModel(
            name="JournalArticle",
        ),
        migrations.DeleteModel(
            name="Preprint",
        ),
        migrations.DeleteModel(
            name="Thesis",
        ),
    ]
