# Generated by Django 5.0.7 on 2025-06-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0008_remove_journalarticle_authors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField(max_length=5000)),
                (
                    "headshot",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("office", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="files/")),
                ("website", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("google_scholar", models.URLField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                ("school", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
