# Generated by Django 5.0.7 on 2025-06-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0009_profile_delete_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="pronouns",
        ),
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(max_length=5000),
        ),
    ]
