# Generated by Django 5.0.7 on 2025-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_profile_delete_author'),
    ]

    operations = [
    ]
