# Generated by Django 5.0.7 on 2025-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_author_reference_referenceauthor_delete_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ReferenceAuthor',
        ),
    ]
