# Generated by Django 5.0.7 on 2025-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_remove_authors_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='references', to='academic.author'),
        ),
    ]
