# Generated by Django 5.0.7 on 2025-07-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_add_authors_field_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='headshot',
        ),
        migrations.AddField(
            model_name='reference',
            name='code',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='slides',
            field=models.FileField(blank=True, upload_to='slides/'),
        ),
    ]
