# Generated by Django 5.0.7 on 2025-07-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_remove_profile_headshot_reference_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.CreateModel(
            name='ReferenceAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.author')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.reference')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('reference', 'author')},
            },
        ),
    ]
