# Generated by Django 5.0.7 on 2025-07-14 03:49

from django.db import migrations


def populate_reference_author_through_model(apps, schema_editor):
    """
    Populate the ReferenceAuthor through model with existing author relationships
    """
    Reference = apps.get_model('academic', 'Reference')
    ReferenceAuthor = apps.get_model('academic', 'ReferenceAuthor')
    
    for reference in Reference.objects.all():
        for order, author in enumerate(reference.authors.all()):
            ReferenceAuthor.objects.create(
                reference=reference,
                author=author,
                order=order
            )


def reverse_populate_reference_author_through_model(apps, schema_editor):
    """
    Reverse operation - clear the through model
    """
    ReferenceAuthor = apps.get_model('academic', 'ReferenceAuthor')
    ReferenceAuthor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_create_reference_author_through_model'),
    ]

    operations = [
        migrations.RunPython(
            populate_reference_author_through_model,
            reverse_populate_reference_author_through_model
        ),
    ]
