# Generated by Django 5.0.7 on 2025-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_populate_reference_author_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='authors_order',
            field=models.CharField(blank=True, help_text='Comma-separated list of author IDs in display order', max_length=1000),
        ),
        migrations.DeleteModel(
            name='ReferenceAuthor',
        ),
    ]
