# Generated by Django 5.0.7 on 2025-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_add_authors_order_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional image for the publication (e.g., graph, diagram)', null=True, upload_to='references/images/'),
        ),
    ]
