# Generated by Django 5.0.7 on 2025-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_add_reference_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
