# Generated by Django 5.0.7 on 2025-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_remove_profile_address_profile_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='alphabetical_authors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='authors_order',
        ),
        migrations.AlterField(
            model_name='reference',
            name='code',
            field=models.URLField(blank=True, help_text='Link to the code repository'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated list of keywords', max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slides',
            field=models.FileField(blank=True, help_text='Optional slides for the publication', upload_to='slides/'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
