# Generated by Django 5.0.7 on 2025-07-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_remove_reference_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='authors',
            field=models.CharField(default='Unknown Author', max_length=1000),
        ),
    ]
