# Generated by Django 5.0.7 on 2025-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_alter_reference_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='alphabetical_order',
            field=models.BooleanField(default=False, help_text='Check if authors are listed in alphabetical order'),
        ),
        migrations.AddField(
            model_name='reference',
            name='shared_first_author',
            field=models.BooleanField(default=False, help_text='Check if first authorship is shared'),
        ),
    ]
