# Generated by Django 5.0.7 on 2025-07-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_collaborator_reference_alphabetical_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
