# Generated by Django 5.0.7 on 2025-07-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_reference_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='collaborators/'),
        ),
    ]
