# Generated by Django 5.0.7 on 2025-07-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_collaborator_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blue_sky',
            field=models.URLField(blank=True, null=True),
        ),
    ]
