# Generated by Django 5.0.7 on 2025-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_profile_blue_sky'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
