# Generated by Django 5.0.7 on 2025-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_profile_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='office',
            new_name='building',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
