# Generated by Django 5.0.7 on 2025-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_rename_office_profile_building_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
