# Generated by Django 5.0.7 on 2025-07-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_profile_occupation_alter_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='long_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
