# Generated by Django 5.0.7 on 2025-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_profile_long_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='long_institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
