# Generated by Django 5.0.7 on 2025-07-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_profile_long_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
