# Generated by Django 5.0.7 on 2025-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_profile_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='poster',
            field=models.FileField(blank=True, help_text='Optional poster for the publication', upload_to='posters/'),
        ),
    ]
