# Generated by Django 5.0.7 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_reference_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='under_construction',
            field=models.BooleanField(default=False, help_text='Show under construction notice on website'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='references/papers/'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='poster',
            field=models.FileField(blank=True, help_text='Optional poster for the publication', upload_to='references/posters/'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='slides',
            field=models.FileField(blank=True, help_text='Optional slides for the publication', upload_to='references/slides/'),
        ),
    ]
