# Generated by Django 5.0.7 on 2025-07-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_profile_short_bio_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.TextField(blank=True, help_text='A stylized quote to display in the footer', max_length=2000, null=True),
        ),
    ]
