# Generated by Django 5.0.7 on 2025-08-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_course_education_experience_grant_service_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='slides',
        ),
    ]
