# Generated by Django 5.0.7 on 2025-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_remove_reference_poster_remove_reference_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, help_text='Title or description of the service', max_length=200),
        ),
    ]
