# Generated by Django 5.0.7 on 2025-08-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(help_text='Type of degree', max_length=20),
        ),
    ]
