# Generated by Django 5.0.7 on 2025-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_alter_education_degree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='related_publications',
            field=models.ManyToManyField(blank=True, help_text='Related publications or papers', to='academic.reference'),
        ),
    ]
