# Generated by Django 5.0.7 on 2025-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_grant_related_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_type_short',
            field=models.CharField(blank=True, help_text='Short form of degree type', max_length=20, null=True),
        ),
    ]
