# Generated by Django 5.0.7 on 2025-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_education_degree_type_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='related_publications',
            field=models.ManyToManyField(blank=True, help_text='Related publications or papers', to='academic.reference'),
        ),
    ]
