# Generated by Django 5.0.7 on 2025-08-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_education_related_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course code (e.g., CS101, MATH 201)', max_length=20, null=True),
        ),
    ]
