# Generated by Django 5.0.7 on 2025-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_alter_course_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-start_date', 'title'], 'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.RemoveField(
            model_name='grant',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='start_year',
        ),
        migrations.AddField(
            model_name='grant',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the grant', null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the grant', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end_year',
            field=models.PositiveBigIntegerField(blank=True, help_text='End year (if applicable)', null=True),
        ),
    ]
