# Generated by Django 5.0.7 on 2025-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0045_alter_grant_options_remove_grant_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_button',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
