# Generated by Django 5.0.7 on 2025-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0046_profile_cv_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='end_year',
        ),
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
