# Generated by Django 5.0.7 on 2025-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0047_remove_service_end_year_service_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_year',
            field=models.PositiveBigIntegerField(blank=True, help_text='End year (if applicable)', null=True),
        ),
    ]
