# Generated by Django 5.0.7 on 2025-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0049_quote_remove_profile_quote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_author',
            new_name='author',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.TextField(blank=True, help_text='A stylized quote to display in the footer', max_length=2000, null=True),
        ),
    ]
