# Generated by Django 5.0.7 on 2025-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0050_rename_quote_author_quote_author_quote_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='figures/')),
                ('caption', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='talk',
            name='poster',
            field=models.FileField(blank=True, help_text='Upload poster file', null=True, upload_to='talks/posters/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
