# Generated by Django 5.0.7 on 2025-10-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0051_figure_profile_headshot_talk_poster_alter_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Professional title', max_length=200)),
                ('institution', models.CharField(help_text='Institution or company', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, help_text='Your relationship to the reference (e.g., PhD Advisor)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Reference',
                'verbose_name_plural': 'Professional References',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('undergrad', 'Undergraduate'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoc', 'Postdoc'), ('highschool', 'High School'), ('other', 'Other')], help_text='Level of the student', max_length=20)),
                ('degree', models.CharField(blank=True, help_text='Degree pursued (e.g., B.S. in Math, PhD in ESE)', max_length=100)),
                ('mentorship_role', models.CharField(blank=True, choices=[('advisor', 'Thesis Advisor'), ('co_advisor', 'Thesis Co-Advisor'), ('committee', 'Committee Member'), ('', 'Informal Mentorship')], help_text='Your role in mentoring this student', max_length=20)),
                ('institution', models.CharField(help_text='Institution student is enrolled at', max_length=200)),
                ('project_title', models.CharField(blank=True, help_text='Title of the research project (optional)', max_length=300)),
                ('start_date', models.DateField(help_text='Start date of mentorship')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if ongoing)', null=True)),
                ('current_position', models.CharField(blank=True, help_text='Current position or status (optional)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
