# Generated by Django 5.0.7 on 2025-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0051_figure_profile_headshot_talk_poster_alter_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee_name', models.CharField(help_text='Full name of the mentee', max_length=200)),
                ('mentee_level', models.CharField(choices=[('high_school', 'High School Student'), ('undergraduate', 'Undergraduate Student'), ('masters', "Master's Student"), ('phd', 'PhD Student'), ('postdoc', 'Postdoctoral Researcher'), ('junior_faculty', 'Junior Faculty'), ('industry', 'Industry Professional'), ('other', 'Other')], default='other', max_length=20)),
                ('institution', models.CharField(help_text='Institution or organization of the mentee', max_length=200)),
                ('department', models.CharField(blank=True, help_text='Department or unit (optional)', max_length=200, null=True)),
                ('area', models.CharField(blank=True, help_text='Area/topic of mentorship (optional)', max_length=200, null=True)),
                ('start_date', models.DateField(help_text='Start date of the mentorship')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if this mentorship is ongoing')),
                ('outcome', models.CharField(blank=True, help_text='Outcome or placement (optional)', max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mentorship',
                'verbose_name_plural': 'Mentorships',
                'ordering': ['-start_date', 'mentee_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the activity (e.g., workshop, training)', max_length=300)),
                ('organization', models.CharField(help_text='Hosting organization or provider', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, State/Province, Country', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (optional)', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description or focus area')),
                ('url', models.URLField(blank=True, help_text='Link to program or certificate (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Development',
                'verbose_name_plural': 'Professional Development',
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
