# Generated by Django 5.0.7 on 2025-10-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0052_referenceperson_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceperson',
            name='relationship',
            field=models.CharField(choices=[('advisor', 'Ph.D. Advisor'), ('postdoc_mentor', 'Postdoc Mentor'), ('committee_member', 'Committee Member'), ('teaching_mentor', 'Teaching Mentor'), ('research_mentor', 'Research Mentor'), ('other_mentor', 'Other Mentor')], default='other_mentor', max_length=20),
        ),
    ]
