# Generated by Django 5.0.7 on 2025-10-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0053_alter_referenceperson_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceperson',
            name='phone',
        ),
    ]
