# Generated by Django 5.0.7 on 2026-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0054_remove_referenceperson_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the grant or project'),
        ),
        migrations.AddField(
            model_name='grant',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=300, null=True, unique=True),
        ),
    ]
