# Generated by Django 5.0.7 on 2026-02-10 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0055_grant_description_grant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the milestone', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=300, null=True, unique=True)),
                ('date', models.DateField(help_text='Date of the milestone')),
                ('description', models.TextField(blank=True, help_text='A description of the milestone')),
                ('report', models.FileField(blank=True, help_text='Upload report file', null=True, upload_to='milestones/reports/')),
                ('slides', models.FileField(blank=True, help_text='Upload slides file', null=True, upload_to='milestones/slides/')),
                ('figure', models.ForeignKey(blank=True, help_text='Optional figure for the milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.figure')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='academic.grant')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['-date', 'title'],
            },
        ),
    ]
