# Generated by Django 5.0.7 on 2026-02-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0056_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the grant', null=True, upload_to='grants/'),
        ),
    ]
