# Generated by Django 5.0.7 on 2026-02-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0057_grant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='gantt_chart',
            field=models.ImageField(blank=True, help_text='Gantt chart for the grant', null=True, upload_to='grants/gantt_charts/'),
        ),
        migrations.AddField(
            model_name='grant',
            name='short_title',
            field=models.CharField(blank=True, help_text='A shorter title for display purposes', max_length=100, null=True),
        ),
    ]
