# Generated by Django 5.0.7 on 2026-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0058_grant_gantt_chart_grant_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='program_manager',
            field=models.CharField(blank=True, help_text='Program manager at the funding agency', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='sponsor_logo',
            field=models.ImageField(blank=True, help_text='Logo of the sponsoring organization', null=True, upload_to='grants/sponsor_logos/'),
        ),
    ]
