# Generated by Django 5.0.7 on 2026-02-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0059_grant_program_manager_grant_sponsor_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='gantt_chart',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='figure',
        ),
    ]
