# Generated by Django 5.0.7 on 2026-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0060_remove_grant_gantt_chart_remove_milestone_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='password',
            field=models.CharField(blank=True, help_text="Password for this grant's page (if password protected)", max_length=128),
        ),
        migrations.AddField(
            model_name='grant',
            name='password_protected',
            field=models.BooleanField(default=False, help_text="Enable password protection for this grant's page"),
        ),
    ]
