# Generated by Django 5.0.7 on 2026-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0061_grant_password_grant_password_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short URL slug for sharing', max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short URL slug for sharing', max_length=300, null=True, unique=True),
        ),
    ]
