# Generated by Django 5.0.7 on 2026-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0062_reference_slug_talk_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_publications',
            field=models.BooleanField(default=True, help_text='Show the Publications section on the homepage'),
        ),
    ]
