# Generated by Django 5.0.7 on 2026-08-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0062_reference_slug_talk_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the award, fellowship, or nomination",
                        max_length=300,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Awarding body, conference, or institution",
                        max_length=300,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "date_range",
                    models.CharField(
                        blank=True,
                        help_text="Period the award covers, e.g. 'August 2017 – September 2022'. Used instead of the year.",
                        max_length=100,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        help_text="Parenthetical or explanatory prose. Supports [[ref:slug]].",
                    ),
                ),
                (
                    "pre_gt_hire",
                    models.BooleanField(
                        blank=True,
                        help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                        null=True,
                    ),
                ),
                (
                    "cv_ref_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering; lower numbers print first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "ordering": ["order", "-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="DeliveredProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name of the product, e.g. 'Lawvere'",
                        max_length=200,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One-line description printed after the name in the heading.",
                        max_length=500,
                    ),
                ),
                (
                    "sponsor",
                    models.CharField(
                        blank=True,
                        help_text="Sponsor or party the product was delivered to",
                        max_length=300,
                    ),
                ),
                (
                    "date_range",
                    models.CharField(
                        blank=True,
                        help_text="Date range for work performed by the candidate, e.g. 'May 2026 – present'.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Product description. Supports [[ref:slug]].",
                    ),
                ),
                (
                    "maturity",
                    models.TextField(
                        blank=True, help_text="Current maturity of the product."
                    ),
                ),
                (
                    "technical_contribution",
                    models.TextField(
                        blank=True,
                        help_text="Candidate's technical contribution. Supports [[ref:slug]].",
                    ),
                ),
                (
                    "cv_ref_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering; lower numbers print first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivered Product",
                "verbose_name_plural": "Delivered Products",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Innovation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the innovation or contribution",
                        max_length=500,
                    ),
                ),
                (
                    "sponsors_projects_dates",
                    models.CharField(
                        blank=True,
                        help_text="'Sponsors/Projects/Dates' line, e.g. 'DARPA SEAMAN (Aug 2025 – present)'.",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description. Supports [[ref:slug]]."
                    ),
                ),
                (
                    "technical_contributions",
                    models.TextField(
                        blank=True,
                        help_text="Candidate's specific technical contributions. Supports [[ref:slug]].",
                    ),
                ),
                (
                    "cv_ref_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering; lower numbers print first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Technical Innovation",
                "verbose_name_plural": "Technical Innovations",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="attendee_count",
            field=models.CharField(
                blank=True,
                help_text="'Approx. Number of Students/Attendees' column, e.g. '~30'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="curriculum_role",
            field=models.TextField(
                blank=True, help_text="'Role in Curriculum Development' column."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Institution/Organization column. Defaults to the institution above.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="when_taught",
            field=models.CharField(
                blank=True,
                help_text="'When Taught' column, e.g. 'May 2026'. Defaults to the semester and year.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="is_dissertation",
            field=models.BooleanField(
                default=False,
                help_text="Print this degree's thesis in Section I.A (Thesis/Dissertation).",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="thesis_url",
            field=models.URLField(
                blank=True, help_text="Link to the thesis or dissertation record."
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="amount_requested",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="candidate_role_text",
            field=models.CharField(
                blank=True,
                help_text="Candidate's Role, e.g. 'Task Leader (Key Personnel)'. Overrides the role above.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="contribution_to_proposal",
            field=models.TextField(
                blank=True,
                help_text="'Contribution to Proposal' row of the Section IV.B table. Supports [[ref:slug]].",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="contributions",
            field=models.TextField(
                blank=True,
                help_text="'Contributions' row of the Section III.A table. Supports [[ref:slug]].",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="date_abstract_submitted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="date_full_submitted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="full_proposal_note",
            field=models.CharField(
                blank=True,
                help_text="Used instead of the full-proposal date, e.g. 'TBD (due August 25, 2026)' or 'N/A'.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="gt_status",
            field=models.CharField(
                choices=[
                    ("funded", "Funded"),
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("in_preparation", "In preparation"),
                    ("not_selected", "Not selected"),
                ],
                default="funded",
                help_text="Funded awards appear in Section III.A; everything else in Section IV.B.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="pi_name",
            field=models.CharField(
                blank=True,
                help_text="P.I. of record. Defaults to the profile name. One per line for multiple PIs.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="report_series_note",
            field=models.TextField(
                blank=True,
                help_text="Preamble for this award's report series in Section II.A (authorship, sponsor notes).",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="result_note",
            field=models.CharField(
                blank=True,
                help_text="'Result' row, e.g. 'Full proposal recommended; in preparation'.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="solicitation",
            field=models.CharField(
                blank=True,
                help_text="Solicitation number, for proposals.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="task_title",
            field=models.CharField(
                blank=True,
                help_text="Task Title, for Center-style awards.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="authorship_percent",
            field=models.PositiveIntegerField(
                blank=True, help_text="Candidate's share of authorship.", null=True
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="page_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Length in pages, for written reports.", null=True
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="report_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interim_report", "Interim technical report"),
                    ("briefing", "Sponsor briefing"),
                    ("status_report", "Recurring status report"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="slide_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Length in slides, for briefings.", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cv_show_preamble_sections",
            field=models.BooleanField(
                default=True,
                help_text="Print EDUCATION and PROFESSIONAL APPOINTMENTS before Section I. The strict GT format omits both.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="fields_of_interest",
            field=models.TextField(
                blank=True,
                help_text="Semicolon-separated research interests, printed under CURRENT FIELDS OF INTEREST.",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gt_hire_date",
            field=models.DateField(
                blank=True,
                help_text="Georgia Tech hire date. Work completed before this date is marked with *.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="research_program",
            field=models.TextField(
                blank=True,
                help_text="Section IV.A narrative. Blank lines separate paragraphs. Supports [[ref:slug]].",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="arxiv_id",
            field=models.CharField(
                blank=True, help_text="arXiv identifier, e.g. 2501.03890", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="credit_roles",
            field=models.CharField(
                blank=True,
                help_text="CRediT roles, comma separated, e.g. 'conceptualization, methodology, review, and editing'. Rendered as 'Contributed ....'",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="gt_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journal", "Published Journal Papers"),
                    ("invited_conf", "Invited Conference Presentations"),
                    (
                        "proc_refereed",
                        "Conference Presentations with Proceedings (refereed)",
                    ),
                    (
                        "proc_nonrefereed",
                        "Conference Presentations with Proceedings (non-refereed)",
                    ),
                    ("no_proc", "Conference Presentations without Proceedings"),
                    ("submitted", "Submitted Journal Papers in Review"),
                ],
                help_text="Section I.B subsection. Leave blank to derive it from the reference type.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="status_note",
            field=models.CharField(
                blank=True,
                help_text="Publication status, e.g. 'to appear' or 'Submitted to Compositionality'.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="detail",
            field=models.TextField(
                blank=True,
                help_text="Additional prose printed after the entry. Supports [[ref:slug]].",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="gt_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journal_review", "A. Reviewer Work for Technical Journals"),
                    ("conference_review", "B. Reviewer Work for Conferences"),
                    ("session_chair", "C. Conference Session Chairs"),
                    ("special_activity", "D. Special Activities"),
                    (
                        "outside_professional",
                        "E. Outside Professional Activities/Consulting",
                    ),
                    ("civic", "F. Civic Activities"),
                ],
                help_text="Section V subsection. Leave blank to derive it from the service type and role.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="manuscript_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of manuscripts reviewed, e.g. '(1 manuscript)'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="advisor_of_record",
            field=models.CharField(
                blank=True,
                help_text="Advisor of record for the student's degree program.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="appointment_note",
            field=models.CharField(
                blank=True,
                help_text="Nature of the appointment, e.g. 'Summer intern'.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="host_lab",
            field=models.CharField(
                blank=True,
                help_text="Host lab, with its director if relevant.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="research_topic",
            field=models.CharField(
                blank=True,
                help_text="'Research topic: ...'. Defaults to the project title above.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="resulting_publications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Publications resulting from this mentorship, cited as 'see I.B.3.2'.",
                related_name="mentored_students",
                to="academic.reference",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="credit_roles",
            field=models.CharField(
                blank=True,
                help_text="CRediT roles, comma separated, e.g. 'conceptualization, methodology, review, and editing'. Rendered as 'Contributed ....'",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="gt_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("journal", "Published Journal Papers"),
                    ("invited_conf", "Invited Conference Presentations"),
                    (
                        "proc_refereed",
                        "Conference Presentations with Proceedings (refereed)",
                    ),
                    (
                        "proc_nonrefereed",
                        "Conference Presentations with Proceedings (non-refereed)",
                    ),
                    ("no_proc", "Conference Presentations without Proceedings"),
                    ("submitted", "Submitted Journal Papers in Review"),
                ],
                help_text="Section I.B subsection. Leave blank to derive it from the talk type.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Bracketed note after the entry, e.g. 'Invited speaker among 10 others.'",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="pre_gt_hire",
            field=models.BooleanField(
                blank=True,
                help_text="Marks the entry with * (completed before the Georgia Tech hire date). Leave unset to derive it from the date and the profile's GT hire date.",
                null=True,
            ),
        ),
    ]
