# Generated by Django 5.0.7 on 2026-07-29 18:24

import academic.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0063_profile_show_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(storage=academic.storage_backends.PrivateMediaStorage(), upload_to='slides/')),
                ('password_protected', models.BooleanField(default=False, help_text='Check this to require a password to view.')),
                ('password', models.CharField(blank=True, help_text='Required if Password Protected is checked.', max_length=50, null=True)),
            ],
        ),
    ]
