# Generated by Django 5.0.7 on 2026-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add Profile.show_publications.

    The production database already carried a `show_publications` column that no
    migration had created, so a plain AddField aborted the release with
    DuplicateColumn. The column is therefore added through SQL that tolerates it
    already being there, and the trailing statements normalise whatever
    definition it has to the one BooleanField(default=True) expects: NOT NULL,
    every existing row true, and no database-level default (Django drops the
    default after backfilling, so introspection stays in step with the model).

    All four statements are no-ops when the column is already correct, so this
    applies cleanly to a fresh database and to the drifted one alike. The SQL is
    PostgreSQL-specific, which every environment of this project uses.
    """

    dependencies = [
        ("academic", "0063_gt_cv_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'ALTER TABLE "academic_profile" '
                        'ADD COLUMN IF NOT EXISTS "show_publications" boolean;',
                        'UPDATE "academic_profile" SET "show_publications" = true '
                        'WHERE "show_publications" IS NULL;',
                        'ALTER TABLE "academic_profile" '
                        'ALTER COLUMN "show_publications" SET NOT NULL;',
                        'ALTER TABLE "academic_profile" '
                        'ALTER COLUMN "show_publications" DROP DEFAULT;',
                    ],
                    reverse_sql=[
                        'ALTER TABLE "academic_profile" '
                        'DROP COLUMN IF EXISTS "show_publications";',
                    ],
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="profile",
                    name="show_publications",
                    field=models.BooleanField(
                        default=True,
                        help_text="Show the publications list on the home page.",
                    ),
                ),
            ],
        ),
    ]
