# Generated by Django 5.0.7 on 2026-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0063_gt_cv_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_publications",
            field=models.BooleanField(
                default=True, help_text="Show the publications list on the home page."
            ),
        ),
    ]
