# Generated by Django 5.0.7 on 2026-08-12 21:35

import django.db.models.deletion
from django.db import migrations, models


def carry_over_proposals_and_reports(apps, schema_editor):
    """Move proposal and report data onto the models that now own it.

    Proposals used to be Grants with a non-funded gt_status, and technical
    reports used to be Milestones. Both sets of fields are dropped further down
    this migration, so anything already entered is copied across first.
    """
    Grant = apps.get_model("academic", "Grant")
    Milestone = apps.get_model("academic", "Milestone")
    Proposal = apps.get_model("academic", "Proposal")
    TechReport = apps.get_model("academic", "TechReport")

    for grant in Grant.objects.exclude(gt_status="funded"):
        Proposal.objects.create(
            title=grant.title,
            short_title=grant.short_title or "",
            sponsor=grant.funding_agency,
            solicitation=grant.solicitation or "",
            pi_name=grant.pi_name or "",
            candidate_role=grant.candidate_role_text or "Principal Investigator",
            date_abstract_submitted=grant.date_abstract_submitted,
            date_full_submitted=grant.date_full_submitted,
            full_proposal_note=grant.full_proposal_note or "",
            amount_requested=grant.amount_requested,
            currency=grant.currency,
            result=grant.gt_status if grant.gt_status in
                   ("pending", "not_selected", "in_preparation") else "pending",
            result_note=grant.result_note or "",
            start_date=grant.start_date,
            end_date=grant.end_date,
            contribution=grant.contribution_to_proposal or "",
        )

    for milestone in Milestone.objects.exclude(report_type=""):
        TechReport.objects.create(
            grant=milestone.grant,
            title=milestone.title,
            report_type=milestone.report_type,
            date=milestone.date,
            page_count=milestone.page_count,
            slide_count=milestone.slide_count,
            authorship_percent=milestone.authorship_percent,
            description=milestone.description or "",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0065_rename_reference_medium_talk_invited"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("short_title", models.CharField(blank=True, max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
                (
                    "sponsor",
                    models.CharField(
                        help_text="Funding agency or organization", max_length=200
                    ),
                ),
                (
                    "solicitation",
                    models.CharField(
                        blank=True, help_text="Solicitation number", max_length=100
                    ),
                ),
                (
                    "pi_name",
                    models.CharField(
                        blank=True,
                        help_text="PI of record. Defaults to the profile name. One per line for multiple PIs.",
                        max_length=300,
                    ),
                ),
                (
                    "candidate_role",
                    models.CharField(
                        blank=True,
                        default="Principal Investigator",
                        help_text="Candidate's Role, e.g. 'Co-PI'.",
                        max_length=200,
                    ),
                ),
                ("date_abstract_submitted", models.DateField(blank=True, null=True)),
                ("date_full_submitted", models.DateField(blank=True, null=True)),
                (
                    "full_proposal_note",
                    models.CharField(
                        blank=True,
                        help_text="Used instead of the full-proposal date, e.g. 'TBD (due August 25, 2026)' or 'N/A'.",
                        max_length=200,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("funded", "Funded"),
                            ("recommended", "Full proposal recommended"),
                            ("not_selected", "Not selected"),
                            ("in_preparation", "In preparation"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_note",
                    models.CharField(
                        blank=True,
                        help_text="Free-text 'Result', used instead of the choice above when set.",
                        max_length=300,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Proposed period of performance",
                        null=True,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contribution",
                    models.TextField(
                        blank=True,
                        help_text="'Contribution to Proposal' row. Supports [[ref:slug]].",
                    ),
                ),
                (
                    "cv_ref_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering; lower numbers print first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The award this proposal produced, if it was funded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="academic.grant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "ordering": ["order", "-date_abstract_submitted", "title"],
            },
        ),
        migrations.CreateModel(
            name="TechReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("interim_report", "Interim technical report"),
                            ("briefing", "Sponsor briefing"),
                            ("status_report", "Recurring status report"),
                            ("final_report", "Final technical report"),
                            ("other", "Other"),
                        ],
                        default="interim_report",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Length in pages, for written reports.",
                        null=True,
                    ),
                ),
                (
                    "slide_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Length in slides, for briefings.",
                        null=True,
                    ),
                ),
                (
                    "authorship_percent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Candidate's share of authorship.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Supports [[ref:slug]]."),
                ),
                (
                    "report",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                (
                    "slides",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/slides/"
                    ),
                ),
                (
                    "cv_ref_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference such as I.B.3.4.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering within the award; lower prints first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grant",
                    models.ForeignKey(
                        help_text="The award this report was delivered under. Reports are grouped by award.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_reports",
                        to="academic.grant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Report",
                "verbose_name_plural": "Technical Reports",
                "ordering": ["order", "-date", "title"],
            },
        ),
        migrations.AddField(
            model_name="innovation",
            name="grants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Awards this work was carried out under. Used for the 'Sponsors/Projects/Dates' line when that field is left blank.",
                related_name="innovations",
                to="academic.grant",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="cv_show_all_references",
            field=models.BooleanField(
                default=False,
                help_text="List every publication regardless of status. When off, only accepted and published work appears, plus journal articles and preprints in review.",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="publication_date",
            field=models.DateField(
                blank=True,
                help_text="Full date, used to order entries correctly within a year. Falls back to the year alone when blank.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="refereed",
            field=models.BooleanField(
                default=False, help_text="Check if the venue is refereed"
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_review", "In review"),
                    ("accepted", "Accepted"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="attendee_count",
            field=models.CharField(
                blank=True,
                help_text="Approximate attendance, e.g. '~30'. Used in the Knowledge Sharing table.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="curriculum_role",
            field=models.TextField(
                blank=True,
                help_text="'Role in Curriculum Development' column, for tutorials and workshops listed under Knowledge Sharing.",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="proceedings",
            field=models.BooleanField(
                default=False,
                help_text="Check if the presentation appeared in conference proceedings",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="The paper this presentation is of. Linked papers are cited once, under the paper's own entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presentations",
                to="academic.reference",
            ),
        ),
        migrations.AlterField(
            model_name="innovation",
            name="sponsors_projects_dates",
            field=models.CharField(
                blank=True,
                help_text="'Sponsors/Projects/Dates' line. Derived from the linked awards when blank.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="medium",
            field=models.CharField(
                choices=[
                    ("journal_article", "Journal Article"),
                    ("conference_proceedings", "Conference Proceedings"),
                    ("preprint", "Preprint"),
                    ("book", "Book"),
                    ("book_chapter", "Book Chapter"),
                    ("technical_report", "Technical Report"),
                    ("thesis", "Thesis"),
                    ("other", "Other"),
                ],
                max_length=40,
            ),
        ),
        migrations.RunPython(carry_over_proposals_and_reports, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name="grant",
            name="amount_requested",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="contribution_to_proposal",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="date_abstract_submitted",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="date_full_submitted",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="full_proposal_note",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="gt_status",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="result_note",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="solicitation",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="authorship_percent",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="cv_ref_slug",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="page_count",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="report_type",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="slide_count",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="gt_category",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="status_note",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="gt_category",
        ),
    ]
