# Generated by Django 5.0.7 on 2026-08-12 23:45

from django.db import migrations, models


def carry_over_reviews(apps, schema_editor):
    """Move reviewing work off Service and onto the new Review model.

    Service used to carry `gt_category`, including two reviewing categories that
    now belong to Review. Those rows are converted and the originals removed, so
    a review does not end up printed under Special Activities by the fallback.
    Every other row keeps its category under the new field name.
    """
    Service = apps.get_model("academic", "Service")
    Review = apps.get_model("academic", "Review")

    for service in Service.objects.filter(
            gt_category__in=("journal_review", "conference_review")):
        Review.objects.create(
            venue=service.organization,
            kind=service.gt_category,
            role=service.title or "",
            year=service.year,
            end_year=service.end_year,
            manuscript_count=service.manuscript_count,
            detail=service.detail or "",
        )
    Service.objects.filter(
        gt_category__in=("journal_review", "conference_review")).delete()

    for service in Service.objects.exclude(gt_category=""):
        service.category = service.gt_category
        service.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0067_seed_reference_classification"),
    ]

    operations = [

        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        help_text="Journal, conference, or funding agency, e.g. 'Automatica'",
                        max_length=300,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("journal_review", "Journal peer review"),
                            ("conference_review", "Conference peer review"),
                            ("editorial_board", "Editorial board member"),
                            ("guest_editor", "Guest editor"),
                            ("area_chair", "Area chair / associate editor"),
                            ("program_committee", "Program committee member"),
                            ("grant_panel", "Grant review panel"),
                            ("other", "Other"),
                        ],
                        default="journal_review",
                        max_length=30,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Printed instead of the kind when set, e.g. 'Associate Editor'.",
                        max_length=100,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="For ongoing appointments.", null=True
                    ),
                ),
                (
                    "manuscript_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of manuscripts handled, e.g. '(1 manuscript)'.",
                        null=True,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Additional prose. Supports [[ref:slug]]."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review / Editorial Work",
                "verbose_name_plural": "Reviews / Editorial Work",
                "ordering": ["-year", "venue"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_format",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("workshop", "Workshop"),
                    ("tutorial", "Tutorial"),
                    ("short_course", "Short course"),
                    ("summer_school", "Summer school"),
                    ("seminar_series", "Seminar series"),
                    ("guest_lecture", "Guest lecture"),
                    ("other", "Other"),
                ],
                default="course",
                help_text="What was taught. Anything other than a course is named in the Knowledge Sharing table, e.g. 'Applied Category Theory (workshop)'.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="custom_cv",
            field=models.FileField(
                blank=True,
                help_text="A hand-made CV to serve instead of the generated one. Only used when 'use custom cv' is ticked.",
                null=True,
                upload_to="profile/custom/",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="use_custom_cv",
            field=models.BooleanField(
                default=False,
                help_text="Serve the uploaded custom CV instead of generating one from the database.",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("session_chair", "Conference Session Chairs"),
                    ("special_activity", "Special Activities"),
                    (
                        "outside_professional",
                        "Outside Professional Activities/Consulting",
                    ),
                    ("civic", "Civic Activities"),
                ],
                help_text="Section V subsection. Leave blank to derive it from the service type and role.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv",
            field=models.FileField(
                blank=True,
                help_text="The generated CV. Overwritten every time the CV is rebuilt.",
                null=True,
                upload_to="profile/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_button",
            field=models.BooleanField(
                blank=True,
                help_text="Show the Download CV button. Leave unset to show it.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_show_preamble_sections",
            field=models.BooleanField(
                default=True,
                help_text="Print EDUCATION and PROFESSIONAL APPOINTMENTS before Section I. The strict promotion-packet format omits both.",
            ),
        ),
        migrations.RunPython(carry_over_reviews, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="award",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="course",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="education",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gt_hire_date",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="service",
            name="gt_category",
        ),
        migrations.RemoveField(
            model_name="service",
            name="manuscript_count",
        ),
        migrations.RemoveField(
            model_name="service",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pre_gt_hire",
        ),
        migrations.RemoveField(
            model_name="talk",
            name="pre_gt_hire",
        ),
    ]
