# Generated by Django 5.0.7 on 2026-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0068_review_remove_award_pre_gt_hire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mastodon",
            field=models.URLField(
                blank=True,
                help_text="Full profile URL, e.g. https://mathstodon.xyz/@you — not the @you@server handle.",
                null=True,
            ),
        ),
    ]
