# Generated by Django 5.0.7 on 2026-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0069_profile_mastodon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Matches the demo's static assets and template, e.g. 'coordination-sheaf'.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "blurb",
                    models.TextField(
                        blank=True, help_text="Teaser copy shown under the title."
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Small print under the call to action, e.g. device requirements.",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this demo's teaser on the landing page.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering; lower numbers print first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demo",
                "verbose_name_plural": "Demos",
                "ordering": ["order", "title"],
            },
        ),
    ]
