# Generated by Django 5.0.7 on 2026-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0071_seed_coordination_sheaf_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cv_show_all_references",
            field=models.BooleanField(
                default=False,
                help_text="Also list conference papers in review and preprints that are not under review, each in a subsection of its own. When off, only accepted and published work appears, plus journal articles and preprints in review.",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_review", "In review"),
                    ("accepted", "Accepted"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                help_text="For a preprint: 'In review' while it is submitted somewhere (put the venue in Journal), 'Published' if it is posted but not under review.",
                max_length=20,
            ),
        ),
    ]
