# Generated by Django 5.0.7 on 2026-10-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0072_reference_status_help_preprints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_review", "In review"),
                    ("accepted", "Accepted"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                help_text="For a preprint: 'In review' while it is submitted somewhere (put the venue in Journal); 'Published' or 'Rejected' if it is posted with no submission pending, which lists it under Preprints.",
                max_length=20,
            ),
        ),
    ]
