# Generated by Django 5.0.7 on 2026-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0073_preprint_status_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="attendee_count",
            field=models.CharField(
                blank=True,
                help_text="Approximate enrollment or attendance, e.g. '~30'.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_format",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("workshop", "Workshop"),
                    ("tutorial", "Tutorial"),
                    ("short_course", "Short course"),
                    ("summer_school", "Summer school"),
                    ("seminar_series", "Seminar series"),
                    ("guest_lecture", "Guest lecture"),
                    ("other", "Other"),
                ],
                default="course",
                help_text="What was taught. Anything other than a course is named in the Teaching list, e.g. 'Applied Category Theory (workshop)'.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="curriculum_role",
            field=models.TextField(
                blank=True,
                help_text="Role, printed under the title, e.g. 'Instructor of Record; designed the course'. Defaults to the role above.",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Where it was taught, as the CV names it. Defaults to the institution above.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="when_taught",
            field=models.CharField(
                blank=True,
                help_text="Date printed beside the entry, e.g. 'May 2026'. Defaults to the semester and year.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="deliveredproduct",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="is_dissertation",
            field=models.BooleanField(
                default=False,
                help_text="Print this degree's thesis under it in Education.",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="contributions",
            field=models.TextField(
                blank=True,
                help_text="Contributions, printed under the award in Funded Projects. Supports [[ref:slug]].",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="report_series_note",
            field=models.TextField(
                blank=True,
                help_text="Note opening this award's series under Technical Reports and Briefings (authorship, sponsor notes).",
            ),
        ),
        migrations.AlterField(
            model_name="innovation",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_show_all_references",
            field=models.BooleanField(
                default=False,
                help_text="Also list conference papers in review (under Papers Under Review) and preprints that are not under review (under Preprints). When off, only accepted and published work appears, plus journal articles and preprints in review.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_show_preamble_sections",
            field=models.BooleanField(
                default=True,
                help_text="Print Education and Appointments at the top of the CV. The dissertation is listed under its degree, so it is left out too when off.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fields_of_interest",
            field=models.TextField(
                blank=True,
                help_text="Semicolon-separated research interests, printed under Research Interests.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="research_program",
            field=models.TextField(
                blank=True,
                help_text="Research Program Development narrative, printed under Sponsored Research. Blank lines separate paragraphs. Supports [[ref:slug]].",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("session_chair", "Conference Organization and Session Chairs"),
                    ("special_activity", "Other Professional Service"),
                    (
                        "outside_professional",
                        "Consulting and Outside Professional Activities",
                    ),
                    ("civic", "Community Service"),
                ],
                help_text="Service subsection. Leave blank to derive it from the service type and role.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="resulting_publications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Publications resulting from this mentorship, cited by number, e.g. '[J3]'.",
                related_name="mentored_students",
                to="academic.reference",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="attendee_count",
            field=models.CharField(
                blank=True,
                help_text="Approximate attendance, e.g. '~30'. Used for tutorials under Teaching.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="curriculum_role",
            field=models.TextField(
                blank=True,
                help_text="Role, for tutorials, which the CV lists under Teaching.",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="techreport",
            name="cv_ref_slug",
            field=models.SlugField(
                blank=True,
                help_text="Cross-reference handle. Write [[ref:this-slug]] in any CV prose field to produce a live reference to this entry's number, such as [J3].",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
